# Telegram Bot Configuration
telegram.bot.username=ben4in_bot
telegram.bot.token=YOUR_TELEGRAM_TOKEN_HERE
# Gemini API Key
geminiApiKey=YOUR_API_KEY_HERE

spring.profiles.active=dev

app.api.gemini.base-url=https://generativelanguage.googleapis.com
app.api.gemini.timeout-seconds=5

spring.main.allow-bean-definition-overriding=true